name: '[PR] Validation'
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "VERSION_BEFORE=$(jq -r '.packageDirectories[0].versionNumber' sfdx-project.json)" >> $GITHUB_ENV
      - name: Print Output (Before)
        run: |
          for dir in $(jq -r '.packageDirectories[].path' sfdx-project.json); do
            version=$(jq -r --arg dir "$dir" '.packageDirectories[] | select(.path == $dir) | .versionNumber' sfdx-project.json)
            echo "Package directory: $dir, Version number: $version"
          done
      - name: Test Local Action
        uses: ./
      - name: Print Output (After)
        run: |
          for dir in $(jq -r '.packageDirectories[].path' sfdx-project.json); do
            version=$(jq -r --arg dir "$dir" '.packageDirectories[] | select(.path == $dir) | .versionNumber' sfdx-project.json)
            echo "Package directory: $dir, Version number: $version"
          done
      - run: |
          echo "VERSION_AFTER=$(jq -r '.packageDirectories[0].versionNumber' sfdx-project.json)" >> $GITHUB_ENV

      - name: Verify Version Number
        run: |
          if [ "${{ env.VERSION_BEFORE }}" = "${{ env.VERSION_AFTER }}" ]; then
            echo "::error::Version was not changed (${{ env.VERSION_BEFORE }})"
            exit 1
          else
            echo "Version was changed. Before: '${{ env.VERSION_BEFORE }}'. After: '${{ env.VERSION_AFTER }}'"
            exit 0
          fi
