name: Test
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print Output (Before)
        run: |
          for dir in $(jq -r '.packageDirectories[].path' sfdx-project.json); do
            version=$(jq -r --arg dir "$dir" '.packageDirectories[] | select(.path == $dir) | .versionNumber' sfdx-project.json)
            echo "Package directory: $dir, Version number: $version"
          done

      - name: Test Local Action
        uses: sopra-steria-salesforce/sf-unlocked-package-version-updater@v2
      - name: Print Output (After)
        run: |
          for dir in $(jq -r '.packageDirectories[].path' sfdx-project.json); do
            version=$(jq -r --arg dir "$dir" '.packageDirectories[] | select(.path == $dir) | .versionNumber' sfdx-project.json)
            echo "Package directory: $dir, Version number: $version"
          done
