name: 'test'
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sopra-steria-salesforce/sf-unlocked-package-version-updater@v2
      - run: cat sfdx-project.json
